### ISSUE TITLE
A request for another repo because there the issues tab was not open

### ISSUE THREAD

**Issue by ayuuuvauuu** [pagankeymaster/nightly#4]
Sorry, I know its not the rule, But its a reques

So i want you to upload a .zip file for your lambda-wallpapers repo 

Because the size of it is over my daily data usage limit.

It would be really nice if you could do that .

Thx in advance

**Comment by dharmx** [comment]
Will do.

**Comment by dharmx** [comment]
Hello again! 

I just came across this [this](https://download-directory.github.io). Just paste the directory you want to download like `https://github.com/pagankeymaster/lambda-wallpapers/tree/main/lagtrain` for instance and it should download a zipped version of that folder. Also, I believe you can already download a ZIP file from the "Code" button.
And, GitHub won't allow me to upload a large sized file (< 25MB).

Let me know if this works out for you.

Regards.

**Comment by dharmx** [comment]
Also the Issues tab should be up now!

**Comment by ayuuuvauuu** [comment]
Thanks you for your responce ,
But i have figured out a different method of downloading a large repo,
I used https://download-directory.github.io/ and downloaded the repo in parts. 
Btw thx again . Hoping to see more projects like this. 
Have a nice day.

**Comment by ayuuuvauuu** [comment]
Sorry i didn't saw the comment's url . Btw my work was done
